# Generated by Django 5.1.1 on 2025-03-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес продавца'),
        ),
    ]
