# Generated by Django 5.1.1 on 2025-04-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_seller_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('confirmed', 'Подтвержден'), ('shipped', 'Отправлен'), ('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], default='processing', max_length=20),
        ),
    ]
