# Generated by Django 5.1.1 on 2025-03-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_created_at_category_slug_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='шт', max_length=20),
        ),
    ]
