# Generated by Django 5.1.1 on 2025-04-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('confirmed', 'Подтвержден'), ('canceled', 'Отменен')], default='processing', max_length=20),
        ),
    ]
