# Generated by Django 5.1.1 on 2025-04-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_orderitem_cancel_reason_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
    ]
