# Generated by Django 5.1.1 on 2025-05-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_orderitem_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=12, editable=False, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='qwe', editable=False, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
