# Generated by Django 5.1.1 on 2025-03-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('shipped', 'Отправлен'), ('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], default='processing', max_length=20),
        ),
    ]
