# Generated by Django 5.1.1 on 2025-03-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_available',
            field=models.BooleanField(default=False, verbose_name='Доступна доставка'),
        ),
    ]
