# Generated by Django 5.1.1 on 2025-05-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_message_is_read'),
        ('products', '0012_add_review_moderation_fields'),
    ]

    operations = [
    ]
