# Generated by Django 5.1.1 on 2025-05-21 09:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_merge_20250521_1237'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ai_suggestion',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_moderated',
        ),
        migrations.RemoveField(
            model_name='review',
            name='moderated_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='moderated_by',
        ),
        migrations.RemoveField(
            model_name='review',
            name='moderation_notes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='moderation_status',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='PendingReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_checked', models.BooleanField(default=False)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_reviews_authored', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
