# Generated by Django 5.1.1 on 2025-05-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_review_ai_suggestion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingReview',
        ),
    ]
