# Generated by Django 5.1.1 on 2025-05-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_product_latitude_remove_product_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerapplicationdocument',
            name='application',
        ),
        migrations.DeleteModel(
            name='SellerApplication',
        ),
        migrations.DeleteModel(
            name='SellerApplicationDocument',
        ),
    ]
