# Generated by Django 5.1.1 on 2025-05-31 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_review_admin_feedback_review_moderated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'recipient', 'status')},
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('author', 'recipient'), name='unique_approved_review'),
        ),
    ]
