# Generated by Django 5.1.1 on 2025-01-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='privacy_policy_agreed',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку данных'),
        ),
    ]
