# Generated by Django 5.1.1 on 2025-02-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_customuser_patronymic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerecord',
            name='average_speed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
