# Generated by Django 5.1.1 on 2025-02-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_routerecord_average_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerecord',
            name='route_distance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
