# Generated by Django 5.1.1 on 2025-02-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_routerecord_route_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerecord',
            name='average_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routerecord',
            name='route_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routerecord',
            name='route_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routerecord',
            name='trip_duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='routerecord',
            name='weather_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
