# Generated by Django 5.1.1 on 2025-02-27 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_product_remove_routerecord_user_delete_warehouse_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
