# Generated by Django 5.1.1 on 2025-03-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, default='Адрес не указан', null=True, verbose_name='Адрес'),
        ),
    ]
