# Generated by Django 5.1.1 on 2025-04-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='show_phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='sshow_phone',
            field=models.BooleanField(default=True, null=True, verbose_name='Показывать телефон другим пользователям'),
        ),
    ]
