# Generated by Django 5.1.1 on 2025-04-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_remove_customuser_sshow_phone_customuser_show_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='Средний рейтинг'),
        ),
    ]
