# Generated by Django 5.1.1 on 2025-05-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_pending_seller_verification',
            field=models.BooleanField(default=False, verbose_name='Ожидает верификации как продавец'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='Верифицированный продавец'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seller_rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отказа в верификации'),
        ),
    ]
