# Generated by Django 5.1.1 on 2025-05-23 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_customuser_is_pending_seller_verification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_pending_seller_verification',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='seller_rejection_reason',
        ),
        migrations.AddField(
            model_name='customuser',
            name='seller_application_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подачи заявки'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seller_application_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания к заявке'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seller_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание деятельности продавца'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seller_reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seller_status',
            field=models.CharField(choices=[('not_applied', 'Не подавал заявку'), ('pending', 'На рассмотрении'), ('approved', 'Подтверждён'), ('rejected', 'Отклонён')], default='not_applied', max_length=20, verbose_name='Статус продавца'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='Является продавцом'),
        ),
        migrations.CreateModel(
            name='SellerApplicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='seller_applications/', verbose_name='Изображение')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
