# Generated by Django 5.1.1 on 2025-05-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_remove_customuser_is_pending_seller_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='О себе или хозяйстве'),
        ),
    ]
