# Generated by Django 5.1.1 on 2025-05-24 14:22

import authentication.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_customuser_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=authentication.models.user_media_path, verbose_name='Медиафайл')),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], default='image', max_length=10, verbose_name='Тип медиа')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Медиафайл пользователя',
                'verbose_name_plural': 'Медиафайлы пользователей',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
